'use strict';
(()=>{
  const $=id=>document.getElementById(id);
  const mapBtn=$('mapBtn'), mapPanel=$('mapPanel'), mapClose=$('mapCloseBtn'), mapSetup=$('mapSetup');
  const keyInput=$('gmapKeyInput'), keySave=$('gmapKeySaveBtn'), searchInput=$('mapSearchInput');
  const myLocBtn=$('mapMyLocationBtn'), routePicker=$('routePicker'), routeChoices=$('routeChoices'), routeStart=$('routeStartBtn');
  const navBanner=$('navBanner'), navArrow=$('navArrow'), navDistance=$('navDistance'), navInstruction=$('navInstruction'), navNext=$('navNext');
  const coords=$('gpsCoords'), settingsBottom=$('settingsBtnBottom'), settingsTop=$('settingsBtn');
  const KEY_STORE='aidascam_gmaps_key_v1', ROUTE_STORE='aidascam_nav_route_v1';
  let gmap=null, directionsService=null, directionsRenderer=null, autocomplete=null, routeResult=null, selectedRoute=0;
  let currentPos=null, navRoute=null, navStepIndex=0, navWatch=null, lastNavSpeakKey='', lastAdasSpeakAt=0, lastAdasBucket=null;

  settingsBottom?.addEventListener('click',()=>settingsTop?.click());
  setInterval(()=>{ const d=new Date(); const c=$('clock'); if(c)c.textContent=d.toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'}); },1000);

  function hav(a,b){const R=6371000,p=Math.PI/180,dlat=(b.lat-a.lat)*p,dlon=(b.lng-a.lng)*p;const s=Math.sin(dlat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(s));}
  function stripHtml(s=''){const d=document.createElement('div');d.innerHTML=s;return (d.textContent||'').replace(/\s+/g,' ').trim();}
  function maneuverIcon(m=''){m=String(m).toLowerCase();if(m.includes('left'))return '↰';if(m.includes('right'))return '↱';if(m.includes('uturn'))return '↶';if(m.includes('merge'))return '↗';if(m.includes('roundabout'))return '↻';return '↑';}
  function fmtM(m){if(!Number.isFinite(m))return '-- m';return m>=1000?`${(m/1000).toFixed(m>=10000?0:1)} km`:`${Math.max(0,Math.round(m/10)*10)} m`;}
  function say(text,priority=1){if(!text||!('speechSynthesis'in window))return;const u=new SpeechSynthesisUtterance(text);u.lang='vi-VN';u.rate=1.02;u.pitch=1;u.volume=1;if(priority>=3)window.speechSynthesis.cancel();window.speechSynthesis.speak(u);}
  function navSpeak(step,dist){if(!step)return;const marks=[300,100,30];for(const m of marks){if(dist<=m+12&&dist>=m-35){const k=`${navStepIndex}:${m}`;if(k!==lastNavSpeakKey){lastNavSpeakKey=k;say(`${m===30?'Chuẩn bị. ':''}${stripHtml(step.instructions)}`,2);}break;}}
  }
  function adasVoiceTick(){const el=$('distanceMain');if(!el)return;const d=parseFloat(el.textContent);if(!Number.isFinite(d))return;const now=Date.now();let bucket=null;if(d<=10)bucket=10;else if(d<=15)bucket=15;else if(d<=20)bucket=20;else if(d<=30)bucket=30;else if(d<=50)bucket=50;if(bucket===null)return;if(bucket!==lastAdasBucket||now-lastAdasSpeakAt>18000){lastAdasBucket=bucket;lastAdasSpeakAt=now;say(`Khoảng cách xe phía trước ${Math.round(d)} mét`,bucket<=15?3:1);}}
  setInterval(adasVoiceTick,1200);

  function updateNav(p){if(!navRoute?.steps?.length||!p)return;let step=navRoute.steps[Math.min(navStepIndex,navRoute.steps.length-1)];let dist=hav(p,step.end);if(dist<24&&navStepIndex<navRoute.steps.length-1){navStepIndex++;lastNavSpeakKey='';step=navRoute.steps[navStepIndex];dist=hav(p,step.end);}navBanner.classList.remove('hidden');navArrow.textContent=maneuverIcon(step.maneuver);navDistance.textContent=fmtM(dist);navInstruction.textContent=step.instructions||'Đi thẳng';const nxt=navRoute.steps[navStepIndex+1];navNext.textContent=nxt?`Tiếp theo: ${nxt.instructions}`:'';navSpeak(step,dist);}
  function startNavWatch(){if(navWatch!==null||!navigator.geolocation)return;navWatch=navigator.geolocation.watchPosition(pos=>{currentPos={lat:pos.coords.latitude,lng:pos.coords.longitude};coords.textContent=`${currentPos.lat.toFixed(5)}, ${currentPos.lng.toFixed(5)}`;updateNav(currentPos);},()=>{}, {enableHighAccuracy:true,maximumAge:1000,timeout:10000});}
  startNavWatch();

  async function loadGoogle(){if(window.google?.maps)return true;const key=localStorage.getItem(KEY_STORE)||'';if(!key){mapSetup.classList.remove('hidden');keyInput.value='';return false;}return new Promise((resolve,reject)=>{const cb='__aidascamMapsReady';window[cb]=()=>{delete window[cb];resolve(true)};const s=document.createElement('script');s.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(key)}&libraries=places&language=vi&region=VN&callback=${cb}`;s.async=true;s.defer=true;s.onerror=()=>reject(new Error('Không nạp được Google Maps'));document.head.appendChild(s);});}
  function ensurePos(){return new Promise((resolve,reject)=>{if(currentPos)return resolve(currentPos);if(!navigator.geolocation)return reject(new Error('Thiết bị không có GPS'));navigator.geolocation.getCurrentPosition(p=>{currentPos={lat:p.coords.latitude,lng:p.coords.longitude};resolve(currentPos);},reject,{enableHighAccuracy:true,timeout:10000,maximumAge:1000});});}
  async function initMap(){mapSetup.classList.add('hidden');await loadGoogle();const origin=await ensurePos().catch(()=>({lat:21.0285,lng:105.8542}));const el=$('googleMap');el.innerHTML='';gmap=new google.maps.Map(el,{center:origin,zoom:15,disableDefaultUI:false,mapTypeControl:false,streetViewControl:false,fullscreenControl:false,gestureHandling:'greedy'});directionsService=new google.maps.DirectionsService();directionsRenderer=new google.maps.DirectionsRenderer({map:gmap,suppressMarkers:false,preserveViewport:false,polylineOptions:{strokeWeight:6,strokeOpacity:.88}});autocomplete=new google.maps.places.Autocomplete(searchInput,{fields:['geometry','name','formatted_address','place_id']});autocomplete.addListener('place_changed',()=>{const p=autocomplete.getPlace();if(p?.geometry?.location)computeRoutes(p.geometry.location);});}
  async function computeRoutes(dest){const origin=await ensurePos();directionsService.route({origin,destination:dest,travelMode:google.maps.TravelMode.DRIVING,provideRouteAlternatives:true,drivingOptions:{departureTime:new Date(),trafficModel:'bestguess'}},(result,status)=>{if(status!==google.maps.DirectionsStatus.OK||!result?.routes?.length){alert(`Google Maps chưa tính được tuyến: ${status}`);return;}routeResult=result;selectedRoute=0;directionsRenderer.setDirections(result);directionsRenderer.setRouteIndex(0);renderRouteChoices();});}
  function renderRouteChoices(){routeChoices.innerHTML='';const rs=routeResult?.routes||[];rs.forEach((r,i)=>{const leg=r.legs?.[0];const b=document.createElement('button');b.className='route-choice'+(i===selectedRoute?' active':'');const dur=leg?.duration_in_traffic?.text||leg?.duration?.text||'';const dist=leg?.distance?.text||'';b.innerHTML=`<b>Tuyến ${i+1} · ${dur}</b><span>${dist}${r.summary?` · ${r.summary}`:''}</span>`;b.onclick=()=>{selectedRoute=i;directionsRenderer.setRouteIndex(i);renderRouteChoices();routeStart.disabled=false;};routeChoices.appendChild(b);});routePicker.classList.remove('hidden');routeStart.disabled=false;}
  function serializeSelectedRoute(){const r=routeResult?.routes?.[selectedRoute];if(!r)return null;const steps=[];for(const leg of r.legs||[])for(const s of leg.steps||[])steps.push({instructions:stripHtml(s.instructions),maneuver:s.maneuver||'straight',distanceMeters:s.distance?.value||0,start:{lat:s.start_location.lat(),lng:s.start_location.lng()},end:{lat:s.end_location.lat(),lng:s.end_location.lng()}});return {createdAt:Date.now(),summary:r.summary||'',steps};}
  function teardownMap(){try{directionsRenderer?.setMap(null)}catch{}gmap=null;directionsService=null;directionsRenderer=null;autocomplete=null;routeResult=null;$('googleMap').innerHTML='';routeChoices.innerHTML='';routePicker.classList.add('hidden');searchInput.value='';}
  function closeMap(){mapPanel.classList.add('hidden');mapPanel.setAttribute('aria-hidden','true');teardownMap();}
  async function openMap(){mapPanel.classList.remove('hidden');mapPanel.setAttribute('aria-hidden','false');try{const ok=await loadGoogle();if(ok)await initMap();}catch(e){console.error(e);alert(e.message||e);}}
  mapBtn?.addEventListener('click',openMap);mapClose?.addEventListener('click',closeMap);
  myLocBtn?.addEventListener('click',async()=>{const p=await ensurePos().catch(()=>null);if(p&&gmap){gmap.panTo(p);gmap.setZoom(16);}});
  keySave?.addEventListener('click',()=>{const k=keyInput.value.trim();if(!k){alert('Nhập API key trước.');return;}localStorage.setItem(KEY_STORE,k);location.reload();});
  routeStart?.addEventListener('click',()=>{const r=serializeSelectedRoute();if(!r)return;navRoute=r;navStepIndex=0;localStorage.setItem(ROUTE_STORE,JSON.stringify(r));closeMap();navBanner.classList.remove('hidden');if(currentPos)updateNav(currentPos);say('Bắt đầu điều hướng',1);});
  try{const saved=JSON.parse(localStorage.getItem(ROUTE_STORE)||'null');if(saved?.steps?.length){navRoute=saved;navStepIndex=0;if(currentPos)updateNav(currentPos);}}catch{}
})();
